### ISSUE TITLE
RelayoutGraph() fails with ArgumentException "An item with the same key has already been added"

### ISSUE THREAD

**Issue by jorgensigvardsson** [panthernet/GraphX#53]
This only seem to happen when RelayoutGraph() is called when there are no edges. My solution is to place a guard around the call (`EdgeList.Count > 0`). I'm using GraphX in WPF, and the call stack looks like this:

```
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
at GraphX.PCL.Logic.Algorithms.LayoutAlgorithms.ISOMLayoutAlgorithm`3.Compute(CancellationToken cancellationToken)
at GraphX.PCL.Logic.Models.GXLogicCore`3.Compute(CancellationToken cancellationToken)
at GraphX.Controls.GraphArea`3._relayoutGraph(CancellationToken cancellationToken)
at GraphX.Controls.GraphArea`3._relayoutGraphMain(Boolean generateAllEdges, Boolean standalone)
at OurView.OnAutoLayoutRequested() in C:\Project\OurView.xaml.cs:line 370
```

It looks like the offending call is here: https://github.com/panthernet/GraphX/blob/32384552f214bd73d75a346bfba1f92bdf883a5c/GraphX.PCL.Logic/Algorithms/LayoutAlgorithms/FDP/ISOMLayoutAlgorithm.cs#L54
Not sure why it's being added twice to the dictionary. 

The code up to this point has been:

```
var nodeControl = new VertexControl(nodeViewModel);
GraphControl.Add(nodeViewModel, nodeControl);
nodeControl.Position = someValue;
```

Then it crashes on

```
GraphControl.RelayoutGraph();
```

My gut feeling is that some edge case is missed in the layout algorithm. It only throws when I have a single unconnected node in the layout!

Sorry for the vagueness!

**Comment by panthernet** [comment]
Thanks for report. I'll take a look.

**Comment by panthernet** [comment]
Took much more time than i'd expected to take a look :) I think it happens because the VertexPositions list is already seeded with values (which was added as a feature some time ago) and the algorithm logic don't reflect recent changes. Thanks for spotting, fixed!
