### ISSUE TITLE
ArgumentNullException for LayoutAlgorithmTypeEnum.Tree

### ISSUE THREAD

**Issue by MrZander** [panthernet/GraphX#91]
Does anyone have an example of the Tree layout algorithm?  Or is there some place that defines what each layout algorithm _requires_?  

```
 "Value cannot be null.\r\nParameter name: dictionary"
    at System.Collections.Generic.Dictionary`2..ctor(IDictionary`2 dictionary, IEqualityComparer`1 comparer)
    at System.Collections.Generic.Dictionary`2..ctor(IDictionary`2 dictionary)
    at GraphX.PCL.Logic.Algorithms.LayoutAlgorithms.SimpleTreeLayoutAlgorithm`3.Compute(CancellationToken cancellationToken)
    at GraphX.PCL.Logic.Models.GXLogicCore`3.Compute(CancellationToken cancellationToken)
    at GraphX.Controls.GraphArea`3._relayoutGraph(CancellationToken cancellationToken)
    at GraphX.Controls.GraphArea`3._relayoutGraphMain(Boolean generateAllEdges, Boolean standalone)
    at GraphX.Controls.GraphArea`3.GenerateGraph(TGraph graph, Boolean generateAllEdges, Boolean dataContextToDataItem)
    at Project.Views.Trace.ImpactVisualizer..ctor(ImpactVisualizerViewModel vm) in C:\LocalCode\Project\ALHP_Inventory\Views\Traceability\ImpactVisualizer.xaml.cs:line 70
    at Project.ViewModels.MainWindowViewModel.<>c.<get_ShowTraceabilityImpactCommand>b__105_0() in C:\LocalCode\Project\Project\Project\ViewModels\MainWindowViewModel.cs:line 382
    at Project.Commands.DelegateCommand.Execute(Object parameter) in C:\LocalCode\Project\Project\Commands\DelegateCommand.cs:line 42
    at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
    at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Here is the code... it's pretty barebones.  
I've tested a few other layout algorithms and they work just fine.
```
core.DefaultLayoutAlgorithm = LayoutAlgorithmTypeEnum.Tree;
core.DefaultLayoutAlgorithmParams = core.AlgorithmFactory.CreateLayoutParameters(LayoutAlgorithmTypeEnum.Tree);
core.DefaultOverlapRemovalAlgorithm = OverlapRemovalAlgorithmTypeEnum.FSA;
core.DefaultOverlapRemovalAlgorithmParams = core.AlgorithmFactory.CreateOverlapRemovalParameters(OverlapRemovalAlgorithmTypeEnum.FSA);
core.DefaultEdgeRoutingAlgorithm = EdgeRoutingAlgorithmTypeEnum.SimpleER;
core.DefaultEdgeRoutingAlgorithmParams = core.AlgorithmFactory.CreateEdgeRoutingParameters(EdgeRoutingAlgorithmTypeEnum.SimpleER);
core.AsyncAlgorithmCompute = false; 
graphArea.LogicCore = core; 
graphArea.GenerateGraph(graph);
```

It has something to do with vertex sizes I believe, but I can't figure out what I am missing, there are no examples of this layout type.

**Comment by MrZander** [comment]
Nevermind.  Your nuget package is just out of date.  I manually compiled the binaries and it works now.

**Comment by alinoureldine** [comment]
Hi, I have the same issue with vertix size. Please @panthernet can you please update the nuget packages. 
@MrZander  if you still have the binaries can you please share them. Thanks

**Comment by panthernet** [comment]
I've uploaded the 2.3.7 release. Will do Nuget version soon after.
